# Generated by Django 6.0.3 on 2026-04-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_road', '0009_userdiagnostic_sub_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeproduct',
            name='end_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='종료일'),
        ),
        migrations.AlterField(
            model_name='financeproduct',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='financeproduct',
            name='notice_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='공고일'),
        ),
        migrations.AlterField(
            model_name='housingproduct',
            name='end_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='접수종료일'),
        ),
        migrations.AlterField(
            model_name='housingproduct',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='housingproduct',
            name='notice_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='모집공고일'),
        ),
        migrations.AlterField(
            model_name='housingproduct',
            name='region',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='공급지역'),
        ),
        migrations.AlterField(
            model_name='userdiagnostic',
            name='region',
            field=models.CharField(choices=[('Seoul', '서울특별시'), ('Busan', '부산광역시'), ('Daegu', '대구광역시'), ('Incheon', '인천광역시'), ('Gwangju', '광주광역시'), ('Daejeon', '대전광역시'), ('Ulsan', '울산광역시'), ('Sejong', '세종특별자치시'), ('Gyeonggi', '경기도'), ('Gangwon', '강원특별자치도'), ('Chungbuk', '충청북도'), ('Chungnam', '충청남도'), ('Jeonbuk', '전북특별자치도'), ('Jeonnam', '전라남도'), ('Gyeongbuk', '경상북도'), ('Gyeongnam', '경상남도'), ('Jeju', '제주특별자치도')], db_index=True, default='Seoul', max_length=20, verbose_name='거주지 (시/도)'),
        ),
        migrations.AlterField(
            model_name='welfareproduct',
            name='end_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='종료일'),
        ),
        migrations.AlterField(
            model_name='welfareproduct',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='welfareproduct',
            name='notice_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='공고일'),
        ),
        migrations.AlterField(
            model_name='welfareproduct',
            name='region',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='지원지역'),
        ),
    ]
