# Generated by Django 6.0.3 on 2026-04-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='employment_types',
            field=models.JSONField(blank=True, default=list, help_text="['employee', 'business', 'unemployed', 'freelancer'] 등"),
        ),
        migrations.AddField(
            model_name='policy',
            name='is_disabled_only',
            field=models.BooleanField(default=False, help_text='장애인 전용 여부'),
        ),
        migrations.AddField(
            model_name='policy',
            name='is_low_income_only',
            field=models.BooleanField(default=False, help_text='기초생활수급자/차상위 전용 여부'),
        ),
        migrations.AddField(
            model_name='policy',
            name='is_non_homeowner_only',
            field=models.BooleanField(default=False, help_text='무주택자 전용 여부'),
        ),
    ]
