# Generated by Django 6.0.3 on 2026-04-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_user_alter_userprofile_ai_persona_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='category',
            field=models.CharField(choices=[('Finance', '금융'), ('Housing', '주거'), ('Welfare', '복지'), ('Employment', '고용/취업'), ('Legal', '법률/상담'), ('Youth', '청년특화'), ('Institution', '제도/민원')], max_length=20),
        ),
    ]
