# Generated by Django 6.0.3 on 2026-04-14 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policyapp', '0003_userprofile_children_count_userprofile_debt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_first_home',
            field=models.BooleanField(default=True, verbose_name='생애최초 주택구입 여부'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_homeless',
            field=models.BooleanField(default=True, verbose_name='현재 무주택 여부'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_pregnant',
            field=models.BooleanField(default=False, verbose_name='임신여부'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
