# Generated by Django 6.0.3 on 2026-04-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sub_region',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='세부 지역'),
        ),
    ]
