# Generated by Django 6.0.3 on 2026-04-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_road', '0008_userdiagnostic_homeless_years_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdiagnostic',
            name='sub_region',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='세부 지역 (시/군/구)'),
        ),
        migrations.AlterField(
            model_name='userdiagnostic',
            name='region',
            field=models.CharField(choices=[('Seoul', '서울특별시'), ('Busan', '부산광역시'), ('Daegu', '대구광역시'), ('Incheon', '인천광역시'), ('Gwangju', '광주광역시'), ('Daejeon', '대전광역시'), ('Ulsan', '울산광역시'), ('Sejong', '세종특별자치시'), ('Gyeonggi', '경기도'), ('Gangwon', '강원특별자치도'), ('Chungbuk', '충청북도'), ('Chungnam', '충청남도'), ('Jeonbuk', '전북특별자치도'), ('Jeonnam', '전라남도'), ('Gyeongbuk', '경상북도'), ('Gyeongnam', '경상남도'), ('Jeju', '제주특별자치도')], default='Seoul', max_length=20, verbose_name='거주지 (시/도)'),
        ),
    ]
