# Generated by Django 6.0.3 on 2026-04-16 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sido', models.CharField(blank=True, max_length=50, null=True)),
                ('sigungu', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('income', models.IntegerField(blank=True, null=True)),
                ('net_assets', models.IntegerField(blank=True, null=True)),
                ('debt', models.IntegerField(blank=True, null=True)),
                ('subscription_count', models.IntegerField(blank=True, null=True)),
                ('subscription_amount', models.IntegerField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=20, null=True)),
                ('children_count', models.IntegerField(default=0)),
                ('homeless_period', models.IntegerField(blank=True, null=True)),
                ('is_pregnant', models.BooleanField(default=False, verbose_name='임신여부')),
                ('is_first_home', models.BooleanField(default=True, verbose_name='생애최초 주택구입 여부')),
                ('is_homeless', models.BooleanField(default=True, verbose_name='현재 무주택 여부')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'policyapp_userprofile',
            },
        ),
    ]
