# Generated by Django 6.0.3 on 2026-04-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Finance', '금융'), ('Housing', '주거'), ('Welfare', '복지')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('age_max', models.IntegerField(blank=True, null=True)),
                ('age_min', models.IntegerField(blank=True, default=0, null=True)),
                ('income_limit', models.IntegerField(blank=True, help_text='합산 연소득 제한 (만원)', null=True)),
                ('asset_limit', models.IntegerField(blank=True, help_text='보유 자산 제한 (만원)', null=True)),
                ('requires_kids', models.BooleanField(default=False)),
                ('marital_status', models.JSONField(blank=True, default=list, help_text="['single', 'newly', 'expecting'] 등")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '정책',
                'verbose_name_plural': '정책 목록',
            },
        ),
    ]
