# Generated by Django 6.0.3 on 2026-04-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_policy_employment_types_policy_is_disabled_only_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름/식별자')),
                ('age', models.IntegerField(default=29, verbose_name='만 나이')),
                ('income', models.IntegerField(default=5000, verbose_name='연소득 (만원)')),
                ('region', models.CharField(default='seoul', max_length=50, verbose_name='지역')),
                ('is_non_homeowner', models.BooleanField(default=True, verbose_name='무주택 여부')),
                ('personal_api_key', models.CharField(blank=True, help_text='이 사람만의 AI 호출 시 사용할 키 (비어있으면 기본값 사용)', max_length=100, null=True)),
                ('ai_persona', models.TextField(blank=True, help_text='AI 비서의 성격이나 특이사항 (예: 매우 친절하게, 법률 용어 위주로 등)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '사용자 프로필',
                'verbose_name_plural': '사용자 프로필 목록',
            },
        ),
        migrations.AddField(
            model_name='policy',
            name='benefit_type',
            field=models.CharField(blank=True, choices=[('Loan', '대출'), ('Grant', '보조금'), ('Savings', '저축')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='평균 금리 (%)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='max_limit',
            field=models.IntegerField(blank=True, help_text='최대 한도/수혜액 (만원)', null=True),
        ),
    ]
