# Generated by Django 6.0.3 on 2026-04-08 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_policy_benefit_type_policy_interest_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ai_persona',
            field=models.TextField(blank=True, help_text='AI 비서의 성격', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='이름/식별자'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='personal_api_key',
            field=models.CharField(blank=True, help_text='사용자 전용 API 키', max_length=100, null=True),
        ),
    ]
