# Generated by Django 6.0.3 on 2026-04-15 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('POLICY', '정책/주거'), ('FINANCE', '금융/대출'), ('USAGE', '사이트 이용'), ('OTHER', '기타')], max_length=20, verbose_name='카테고리')),
                ('question', models.CharField(max_length=200, verbose_name='질문')),
                ('answer', models.TextField(verbose_name='답변')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
            ],
            options={
                'verbose_name': '자주 묻는 질문',
                'verbose_name_plural': '자주 묻는 질문 목록',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='공지 제목')),
                ('content', models.TextField(verbose_name='공지 내용')),
                ('is_important', models.BooleanField(default=False, verbose_name='중요')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '공지사항',
                'verbose_name_plural': '공지사항 목록',
                'ordering': ['-is_important', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='문의 제목')),
                ('content', models.TextField(verbose_name='문의 내용')),
                ('status', models.CharField(choices=[('PENDING', '답변 대기'), ('ANSWERED', '답변 완료'), ('CLOSED', '상담 종료')], default='PENDING', max_length=20, verbose_name='상태')),
                ('admin_answer', models.TextField(blank=True, null=True, verbose_name='관리자 답변')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='답변 일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '1:1 문의',
                'verbose_name_plural': '1:1 문의 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
