# Generated by Django 6.0.3 on 2026-04-16 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', '상담 대기'), ('ACTIVE', '상담 중'), ('CLOSED', '상담 종료')], default='PENDING', max_length=20, verbose_name='상담 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최종 활동')),
                ('counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_rooms_as_counselor', to=settings.AUTH_USER_MODEL, verbose_name='상담사')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms_as_customer', to=settings.AUTH_USER_MODEL, verbose_name='고객')),
            ],
            options={
                'verbose_name': '채팅 상담방',
                'verbose_name_plural': '채팅 상담방 목록',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='메시지 내용')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='전송 시간')),
                ('is_read', models.BooleanField(default=False, verbose_name='읽음 여부')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='발신자')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.chatroom', verbose_name='채팅방')),
            ],
            options={
                'verbose_name': '채팅 메시지',
                'verbose_name_plural': '채팅 메시지 목록',
                'ordering': ['timestamp'],
            },
        ),
    ]
